baseURL = 'https://vk0xOrg.github.io/'
title = 'Personal @ Invdividual'
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Personal @ Invdividual"
description = "Щось пишу, чогось не пишу"
keywords = [ "Blog", "Бложара", "Pussy" ]
author = "v.K."
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowFullTextinRSS = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = true
tocopen = true

  [params.assets]
  favicon = "/favicon.ico"
  favicon16x16 = "/favicon-16x16.png"
  favicon32x32 = "/favicon-32x32.png"
  apple_touch_icon = "/apple-touch-icon.png"
  #safari_pinned_tab = "<link / abs url>"

  [params.label]
  text = "Домівка"
  icon = "/apple-touch-icon.png"
  iconHeight = 35

  [params.homeInfoParams]
  Title = "Вітаннячко 👋"
  Content = "Коли букви перетворюються в слова, біти - в джоулі"

  [[params.socialIcons]]
  name = "mastodon"
  url = "https://mastodon.social/@vasia"

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.editPost]
  URL = "https://github.com/vk0xOrg/vk0xOrg.github.io/content"
  Text = "Внести свої 5коп."
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "categories"
name = "кат."
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "бирки"
url = "/tags/"
weight = 20

# adding search options and configs
[outputs]
home = [ "HTML", "RSS", "JSON" ]
