baseURL: 'https://vk0xOrg.github.io/'
title: Personal @ Invdividual
theme: PaperMod
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
minify:
  disableXML: true
  minifyOutput: true
params:
  env: production
  title: Personal @ Invdividual
  description: 'Щось пишу, чогось не пишу'
  keywords:
    - Blog
    - Бложара
    - Pussy
  author: v.K.
  images:
    - '<link or path of image for opengraph, twitter-cards>'
  DateFormat: 'January 2, 2006'
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowFullTextinRSS: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true
  assets:
    favicon: /favicon.ico
    favicon16x16: /favicon-16x16.png
    favicon32x32: /favicon-32x32.png
    apple_touch_icon: /apple-touch-icon.png
  label:
    text: дописи
    icon: /apple-touch-icon.png
    iconHeight: 35
    #  homeInfoParams:
    #    Title: "Вітаннячко \U0001F44B"
    #    Content: 'Коли букви перетворюються в слова, біти - в джоулі'
  socialIcons:
    - name: mastodon
      url: 'https://mastodon.social/@vasia'
    - name: twitter
      url: 'https://twitter.com/'
    - name: github
      url: 'https://github.com/'
  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true
  editPost:
    URL: 'https://github.com/vk0xOrg/vk0xOrg.github.io/content'
    Text: Внести свої 5коп.
    appendFilePath: true
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys:
      - title
      - permalink
      - summary
      - content
menu:
  main:
    - name: п.р.о.
      url: /about/
      weight: 10
    - identifier: categories
      name: кат.
      url: /categories/
      weight: 20
    - identifier: tags
      name: бирки
      url: /tags/
      weight: 30
    - identifier: search
      name: пошук
      url: /search/
      weight: 40
outputs:
  home:
    - HTML
    - RSS
    - JSON

#some security non-impementation
security:
  exec:
    allow:
      - ^vim$
